/*
 * One-off tool: rasterizes VCR OSD Mono (assets/font/VCR_OSD_MONO_1.001.ttf)
 * into src/font_vcr16x16.h — a 16x16 per-glyph coverage table (0-255 real
 * alpha, unlike font8x8.h's hard 1-bit table) used for scale=2 text (see
 * draw_char in main.c). Not part of the app build; run manually only when
 * regenerating the font (e.g. a newer/different TTF).
 *
 * Needs stb_truetype.h (single-header, public domain, same "stb" family as
 * stb_image.h already vendored in src/) — vendored alongside this file in
 * tools/ for the same reason.
 *
 * Build & run:
 *   zig cc -O2 -I. -o rasterize_vcr_font rasterize_vcr_font.c -lm
 *   ./rasterize_vcr_font path/to/VCR_OSD_MONO_1.001.ttf ../src/font_vcr16x16.h
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define STB_TRUETYPE_IMPLEMENTATION
#include "stb_truetype.h"

#define FIRST 0x20
#define LAST  0x7E
#define NCHARS (LAST - FIRST + 1)
#define CELL  16     /* native target resolution — matches scale=2 (8px * 2) */
#define SS    4      /* supersample factor before box-downsampling */
#define SUPER (CELL * SS)

#define ATLAS_W 512
#define ATLAS_H 512

int main(int argc, char **argv) {
    if (argc < 3) { fprintf(stderr, "usage: %s font.ttf out.h\n", argv[0]); return 1; }

    FILE *f = fopen(argv[1], "rb");
    if (!f) { perror("fopen"); return 1; }
    fseek(f, 0, SEEK_END); long sz = ftell(f); fseek(f, 0, SEEK_SET);
    unsigned char *ttf = malloc(sz);
    fread(ttf, 1, sz, f); fclose(f);

    /* bake_px_height/baseline_row were tuned by eye against a rendered
     * comparison (tools/raw_to_png.py preview) — 0.62/0.72 left the glyph
     * looking tiny and washed-out within its cell; 0.95/0.80 fills the cell
     * the way font8x8_basic's own hand-drawn glyphs already do. */
    float bake_px_height = (float)SUPER * 0.95f;
    unsigned char *atlas = calloc(ATLAS_W * ATLAS_H, 1);
    stbtt_bakedchar chardata[NCHARS];
    int rc = stbtt_BakeFontBitmap(ttf, 0, bake_px_height, atlas, ATLAS_W, ATLAS_H,
                                   FIRST, NCHARS, chardata);
    if (rc <= 0) { fprintf(stderr, "BakeFontBitmap failed/overflowed (rc=%d)\n", rc); return 1; }

    /* yoff is baseline-relative (stb bakes it that way) — this is what
     * makes 'M' sit high and 'y'/'g' descenders sit low correctly, instead
     * of every glyph's own bounding box being placed at the same y=0. */
    int baseline_row = (int)(SUPER * 0.80f);

    unsigned char coverage[NCHARS][CELL][CELL];
    memset(coverage, 0, sizeof(coverage));

    for (int i = 0; i < NCHARS; i++) {
        stbtt_bakedchar *bc = &chardata[i];
        int gw = bc->x1 - bc->x0, gh = bc->y1 - bc->y0;
        unsigned char *cellbuf = calloc(SUPER * SUPER, 1);

        int pen_x = (SUPER - (int)(bc->xadvance + 0.5f)) / 2;
        int dst_x0 = pen_x + (int)(bc->xoff + 0.5f);
        int dst_y0 = baseline_row + (int)(bc->yoff + 0.5f);

        for (int y = 0; y < gh; y++) {
            int dy = dst_y0 + y;
            if (dy < 0 || dy >= SUPER) continue;
            for (int x = 0; x < gw; x++) {
                int dx = dst_x0 + x;
                if (dx < 0 || dx >= SUPER) continue;
                cellbuf[dy*SUPER+dx] = atlas[(bc->y0+y)*ATLAS_W + (bc->x0+x)];
            }
        }

        for (int oy = 0; oy < CELL; oy++)
            for (int ox = 0; ox < CELL; ox++) {
                int sum = 0;
                for (int dy = 0; dy < SS; dy++)
                    for (int dx = 0; dx < SS; dx++)
                        sum += cellbuf[(oy*SS+dy)*SUPER + (ox*SS+dx)];
                coverage[i][oy][ox] = (unsigned char)(sum / (SS*SS));
            }
        free(cellbuf);
    }

    FILE *out = fopen(argv[2], "w");
    fprintf(out, "/* Generated by tools/rasterize_vcr_font.c from VCR OSD Mono.\n");
    fprintf(out, " * 16x16 coverage per glyph (0=transparent..255=opaque) — real per-pixel\n");
    fprintf(out, " * alpha, unlike font8x8.h's hard 1-bit table. Used for scale=2 text only\n");
    fprintf(out, " * (see draw_char in main.c); scale=1 still uses font8x8_basic. */\n");
    fprintf(out, "#pragma once\n");
    fprintf(out, "#include <stdint.h>\n\n");
    fprintf(out, "static const uint8_t font_vcr16x16[%d][%d][%d] = {\n", NCHARS, CELL, CELL);
    for (int i = 0; i < NCHARS; i++) {
        int c = FIRST + i;
        fprintf(out, "  { /* 0x%02x */\n", c);
        for (int row = 0; row < CELL; row++) {
            fprintf(out, "    {");
            for (int col = 0; col < CELL; col++)
                fprintf(out, "%d,", coverage[i][row][col]);
            fprintf(out, "},\n");
        }
        fprintf(out, "  },\n");
    }
    fprintf(out, "};\n");
    fclose(out);
    fprintf(stderr, "wrote %s\n", argv[2]);
    return 0;
}
